### PR TITLE
Add font-size

### PR DESCRIPTION
**Pull request by matEhickey**
Hello, here's my PR that allow changing widgets text size.
I needed it to create a smaller UI.

How to use:
~~~js
<a-gui-button
    width="2.5" height="0.75"
    onclick="testButtonAction" key-code="32"
    value="test button X"
    font-family="Arial"
    textsize="25px"
    margin="0 0 0.05 0"
>
~~~

### CODE REVIEW

**Comment by rdub80** [comment]
@matEhickey Thanks for adding this! Before I merge today - could you rename the parameter **textsize** to **font-size** so we can stay as close as possible to CSS lingo, thanks!

**Comment by matEhickey** [comment]
Yes, I will do it tommorow ! (Sorry for today but I have to leave now)

**Comment by matEhickey** [comment]
That's it.  
Also I would like to know if the toggle events (check and uncheck) that I added are in the correct PR. 
I can remove them if you want, to make a new PR that will be focused on new events. 

I also modified the timing of the toggle, to prevent some bugs when user click a second time on it before the animation end, making data.checked and the visual button in different state. 
I can remove this change if you think it's a bad fix.

**Comment by rdub80** [comment]
Merged your font-size PR  - we should start thinking about not using **px** but **dmm** for VR

see:
https://sizecalc.com/#distance=55.17inches&perceived-size=660.0000547800046dmm&physical-size-units=inches

Once we officially have the dmm value system I will update the readme to reflect font-size as official attribute!

@matEhickey - Let me know if you are up for the math :-)

**Comment by matEhickey** [comment]
Indeed I was not very satisfied with this proportion unit, that why I left the "px" in the string.
Good idea, I totaly forgot about dmm unit, I'll try to implement this when I'll get time, shouldn't be too long.

**Pull request merged**
